### PR TITLE
Signup working

### LINKED ISSUE #1: Feature: Signup
Create signup view and backend for thoughts store.

### PR DESCRIPTION
**Pull request by omriBernstein**
Closes #1

### CODE REVIEW

**Comment by omriBernstein** [comment]
@leafoflegend please code review!

**Comment by leafoflegend** [comment]
@omriBernstein Love the signup route, but how am I supposed to login to my account? Please return the ability to login, and have a seperate screen for signup. Then I can close.

**Comment by omriBernstein** [comment]
How about this?
screen shot 2017-01-09 at 3 32 04 pm

**Comment by omriBernstein** [comment]
@leafoflegend

**Comment by leafoflegend** [comment]
@omriBernstein Wowowow looks so good. Pushing React to the limit. In the future please comment your work in your files as you go. But looks good enough.

**Pull request merged**
